services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bday_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/bday_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
