{{- if and .Values.secret.enabled .Values.secret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.value | b64enc }}
{{- end }}
